import { createWash, type IrisTone } from "@ui-lib/core";
import { forwardRef, useState } from "react";

export interface SoftAvatarProps extends React.HTMLAttributes<HTMLSpanElement> {
	/** An image URL. Falls back to initials when absent or when it fails. */
	src?: string;
	/** A name. First character is used for the fallback; also the accessible name. */
	name?: string;
	/** Diameter in px. */
	size?: number;
	/** Which family the fallback tint comes from. */
	tone?: IrisTone;
	/** A number to make this avatar's wash different from the next one's. Defaults to a hash of the name. */
	seed?: number;
	/** A ring around it, for a selected or active state. */
	ring?: boolean;
}

/**
 * A portrait, or a wash with a letter in it.
 *
 * The fallback is the interesting part. Every avatar component has one — the
 * grey circle with initials — and it is always grey, which means the common case
 * (a system where most people have not uploaded anything) is the one the design
 * spends no time on.
 *
 * Here the fallback is generated by `createWash` from the same seed the rest of
 * the material system uses, so an avatar is a pigment mark with a letter on it.
 * Two people with different names get genuinely different marks, because the
 * seed drives the arc strengths, the silhouette, the noise and the rotation — not
 * just the hue. That is the whole reason the wash generator was worth writing:
 * a fallback that is a small painting is a different kind of placeholder.
 *
 * There is no image cropper and no loading spinner. A failed image falls back to
 * the wash silently, because an avatar that shows a broken-image icon is worse
 * than one that shows a letter.
 *
 * ```tsx
 * <SoftAvatar name="陈奕帆" size={48} />
 * <SoftAvatar src="/iris.png" name="Iris" />
 * ```
 */
export const SoftAvatar = forwardRef<HTMLSpanElement, SoftAvatarProps>(function SoftAvatar(
	{ src, name = "", size = 40, tone = "iris", seed, ring = false, className, style, ...props },
	ref,
) {
	const [failed, setFailed] = useState(false);
	const showImage = src !== undefined && !failed;

	/*
	 * The seed has to be stable for a given name and different between names, or
	 * the same person changes their mark on every render and two people can
	 * collide. A small string hash rather than an index, because an index depends
	 * on the order of a list that the avatar does not know about.
	 */
	const resolvedSeed = seed ?? hashName(name);

	// The capsule is round, so the wash is asked for a circle: lobed at 0 the
	// silhouette is nearly circular, and the square box is clipped to match.
	const wash = createWash({
		hue: toneHue(tone),
		// Small marks get a heavier film. The generator is calibrated for a 190px
		// specimen where the eye reads the whole ring; at 40px the deposit is two
		// device pixels wide and the same weight reads as a pale disc. The weight
		// is a real parameter of the material rather than a display tweak, so it
		// is raised here rather than the result being faded up afterwards.
		weight: size < 56 ? 1 : 0.85,
		seed: resolvedSeed,
		state: "dry",
		size,
	});

	return (
		<span
			{...props}
			ref={ref}
			className={className ? `ui-lib-soft-avatar ${className}` : "ui-lib-soft-avatar"}
			/*
			 * The accessible name goes on the container rather than in a hidden
			 * span beside the letter.
			 *
			 * A hidden span is the usual way and it does not work here: the
			 * avatar is a grid, and a second child takes a grid row of its own,
			 * which pushed the letter out of the bottom of the circle. Measured,
			 * the avatar spanned y=320 to 372 and the letter sat at y=372 —
			 * entirely below it, which is why the portraits rendered as marks
			 * with no initial at all.
			 *
			 * `role="img"` with a label is also more accurate than a span of
			 * text: the whole avatar is one thing to announce, not a letter
			 * followed by a name.
			 */
			role="img"
			aria-label={name ? `头像：${name}` : undefined}
			style={{ width: size, height: size, fontSize: size * 0.42, ...style }}
		>
			{showImage ? (
				<img
					src={src}
					alt={name ? `头像：${name}` : "头像"}
					className="ui-lib-soft-avatar__image"
					onError={() => setFailed(true)}
				/>
			) : (
				<>
					{/* The mark, drawn from the generator's own variables so the
					    component carries no colour of its own. */}
					<span
						className={`${wash.className} ui-lib-soft-avatar__wash`}
						aria-hidden="true"
						style={
							{
								...wash.style,
								/*
								 * The film is sized for a 190px specimen; at avatar sizes it is
								 * thickened so the mark is legible rather than a tint.
								 *
								 * 3.4 was the first value and it was an overcorrection. Measured,
								 * it took the opacity from 0.232 to 0.867 and the result was a
								 * saturated disc that buried its own deposit ring and hid the
								 * letter on top of it — a coloured balloon, not a pigment mark.
								 * The ring is what makes it read as a wash, so the target is the
								 * point where the ring is visible and the letter still is: 1.7.
								 */
								opacity: Number(wash.style["--wash-opacity"] ?? 0.17) * 1.7,
							} as React.CSSProperties
						}
					/>
					<span className="ui-lib-soft-avatar__initial" aria-hidden="true">
						{name.slice(0, 1)}
					</span>
				</>
			)}
		</span>
	);
});

/** A stable, well-spread seed from a name. */
function hashName(name: string): number {
	let hash = 2166136261;
	for (let i = 0; i < name.length; i += 1) {
		hash ^= name.charCodeAt(i);
		hash = Math.imul(hash, 16777619);
	}
	return Math.abs(hash) % 100000;
}

/**
 * The wash needs a colour, and the palette's rungs are indexed by number rather
 * than by name, so the tone is mapped here rather than passed through. Kept as a
 * function so a host that swaps the palette has one place to change.
 */
function toneHue(tone: IrisTone): string {
	switch (tone) {
		case "blossom":
			return "#ffb7c5";
		case "mist":
			return "#9ad9ff";
		default:
			return "#b79cf5";
	}
}

/* -------------------------------------------------------------------- tag -- */

export interface SoftTagProps extends React.HTMLAttributes<HTMLSpanElement> {
	/** `solid` is filled, `soft` is a tint, `outline` is a hairline. */
	variant?: "solid" | "soft" | "outline";
	tone?: IrisTone;
	/** Adds a remove affordance. Called when it is activated. */
	onRemove?: () => void;
	/** The label for that affordance. Defaults to a plain "移除". */
	removeLabel?: string;
	/** A small leading mark, usually an icon. */
	leading?: React.ReactNode;
}

/**
 * A label for something, that sits on the page rather than being part of it.
 *
 * The three variants are three amounts of the same substance rather than three
 * unrelated styles. `soft` is the default and is a wash — the tint is mixed with
 * the page rather than laid on it. `solid` is the same pigment at full strength,
 * which is why it needs a light text colour and is the only one that does.
 * `outline` is the pigment with no body at all, for a tag among many where three
 * filled pills in a row is a wall of colour.
 *
 * A tag with `onRemove` gets a real `<button>`, not a clickable span: it needs to
 * be reachable by Tab and by keyboard activation like any other control, and a
 * span with an `onClick` is neither.
 *
 * ```tsx
 * <SoftTag>水彩</SoftTag>
 * <SoftTag variant="solid" tone="blossom">主色</SoftTag>
 * <SoftTag onRemove={() => drop("paper")}>水彩纸</SoftTag>
 * ```
 */
export const SoftTag = forwardRef<HTMLSpanElement, SoftTagProps>(function SoftTag(
	{
		variant = "soft",
		tone = "iris",
		onRemove,
		removeLabel = "移除",
		leading,
		className,
		children,
		...props
	},
	ref,
) {
	return (
		<span
			{...props}
			ref={ref}
			className={className ? `ui-lib-soft-tag ${className}` : "ui-lib-soft-tag"}
			data-ui-lib-variant={variant}
			data-ui-lib-tone={tone}
		>
			{leading && (
				<span className="ui-lib-soft-tag__leading" aria-hidden="true">
					{leading}
				</span>
			)}
			<span className="ui-lib-soft-tag__label">{children}</span>
			{onRemove && (
				<button
					type="button"
					className="ui-lib-soft-tag__remove"
					aria-label={typeof children === "string" ? `${removeLabel} ${children}` : removeLabel}
					onClick={onRemove}
				>
					<svg viewBox="0 0 10 10" width="8" height="8" aria-hidden="true">
						<path
							d="M1.5 1.5 L8.5 8.5 M8.5 1.5 L1.5 8.5"
							stroke="currentColor"
							strokeWidth="1.6"
							strokeLinecap="round"
						/>
					</svg>
				</button>
			)}
		</span>
	);
});
